# Generated by Django 5.0.7 on 2024-08-02 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.budget'),
        ),
    ]
