# Generated by Django 5.0.7 on 2024-08-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_items_remove_expenses_budget_delete_budget_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'items'},
        ),
        migrations.AddField(
            model_name='items',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
