# Generated by Django 5.0.7 on 2024-08-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_items_options_items_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='count',
            new_name='item_count',
        ),
    ]
