# Generated by Django 5.0.7 on 2024-08-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_count_items_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
